name: PIFA v0.1.0 (push || cron)

on:
  push:
    branches:
      - area

jobs:
  fetch-categories:
    name: Fetch Subdomain Data
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: 1. Fetch categories from API
        id: fetch-api
        run: |
          response=$(curl -s "${{ secrets.REACT_APP_API_URL }}/main/categoryarea")
          echo "$response" > categories.json

      - name: 2. Extract required fields and create matrix
        id: set-matrix
        run: |
          matrix=$(jq -c '[.data[] | {name: .subdomain, id: .id, uppername: (.subdomain | ascii_upcase), title: .nama_kategori_daerah}]' categories.json)
          echo "Generated Matrix: $matrix"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  web-deploy:
    name: Deploy on Area
    needs: fetch-categories
    runs-on: ubuntu-latest

    strategy:
      # max-parallel: 2
      matrix:
        category: ${{ fromJson(needs.fetch-categories.outputs.matrix) }}

    steps:
      - name: 1. Get latest code
        uses: actions/checkout@v4

      - name: 2. Use Node.js v20.12.1
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - name: 3. Export environment variables
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> $GITHUB_ENV
          echo "REACT_APP_MARKERS=${{ secrets.REACT_APP_MARKERS }}" >> $GITHUB_ENV
          echo "REACT_APP_DOMAIN_SUB=https://${{ matrix.category.name }}.pifa.co.id" >> $GITHUB_ENV
          echo "REACT_APP_DOMAIN_SUB_NAME=${{ matrix.category.title }}" >> $GITHUB_ENV
          echo "REACT_APP_DOMAIN_SUB_ID=${{ matrix.category.id }}" >> $GITHUB_ENV
          echo "REACT_APP_GTAG_SUB=${{ secrets[format('GTAG_{0}', matrix.category.uppername)] }}" >> $GITHUB_ENV

      - name: 4. Installing required packages
        run: npm install

      - name: 5. Generate latest sitemap
        run: node update-slugs.js
        env:
          REACT_APP_DOMAIN_SUB: https://${{ matrix.category.name }}.pifa.co.id
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: 6. Kill any process using port 45678
        run: |
          sudo lsof -i tcp:45678 | grep LISTEN | awk '{print $2}' | xargs sudo kill -9 || true

      - name: 7. Builds the app for production
        run: CI= npm run spagen

      - name: 8. List output files
        run: find build/ -print

      - name: 9. Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: "ftp_${{ matrix.category.name }}"
          password: ${{ secrets[format('FTP_PASSWORD_{0}', matrix.category.uppername)] }}
          local-dir: build/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**

      - name: 10. Commit and push updated sitemap.xml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet public/sitemap.xml; then
            echo "No changes detected in sitemap.xml. Skipping commit."
          else
            git add public/sitemap.xml
            git commit -m "Update sitemap.xml from GitHub Actions"
            git push origin area
          fi
